BEGIN
    INSERT ALL
        INTO LOAD_STEP (STEP_CODE, STEP_NUMBER, DESCRIPTION, CREATE_TS) VALUES ('VALIDATE', 1, 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STEP (STEP_CODE, STEP_NUMBER, DESCRIPTION, CREATE_TS) VALUES ('PROCESS_MAPPED', 2, 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STEP (STEP_CODE, STEP_NUMBER, DESCRIPTION, CREATE_TS) VALUES ('PROCESS_NON_MAPPED', 3, 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STEP (STEP_CODE, STEP_NUMBER, DESCRIPTION, CREATE_TS) VALUES ('TRANSFORM_INLINE', 4, 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STEP (STEP_CODE, STEP_NUMBER, DESCRIPTION, CREATE_TS) VALUES ('TRANSFORM_AGGREGATE', 5, 'ASDF', SYSTIMESTAMP)
    SELECT * FROM DUAL;
    
    COMMIT;
END;