BEGIN
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_01', 'US_ACCT_01', 'account 01', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_02', 'US_ACCT_02', 'account 02', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_03', 'US_ACCT_03', 'account 03', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_04', 'US_ACCT_04', 'account 04', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_05', 'US_ACCT_05', 'account 05', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_06', 'US_ACCT_06', 'account 06', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_07', 'US_ACCT_07', 'account 07', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_08', 'US_ACCT_08', 'account 08', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_09', 'US_ACCT_09', 'account 09', SYSTIMESTAMP);
    INSERT INTO account (account_nbr, account_code, account_name, create_ts) VALUES ('ACCT_NBR_10', 'US_ACCT_10', 'account 10', SYSTIMESTAMP);
    
    EXECUTE IMMEDIATE 'ALTER TABLE account MODIFY id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY';
    INSERT INTO account (id, account_nbr, account_code, account_name, create_ts) VALUES (-99, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', SYSTIMESTAMP);
    INSERT INTO account (id, account_nbr, account_code, account_name, create_ts) VALUES (-1, 'ALL', 'ALL', 'ALL', SYSTIMESTAMP);
    EXECUTE IMMEDIATE 'ALTER TABLE account MODIFY id NUMBER(19,0) GENERATED ALWAYS AS IDENTITY';

    COMMIT;
END;
