BEGIN
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (1, 'FAC_NBR_01','US_TEST_01', 'TEST FACILITY 1', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (2, 'FAC_NBR_02','US_TEST_02', 'TEST FACILITY 2', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (3, 'FAC_NBR_03','US_TEST_03', 'TEST FACILITY 3', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (4, 'FAC_NBR_04','US_TEST_04', 'TEST FACILITY 4', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (5, 'FAC_NBR_05','US_TEST_05', 'TEST FACILITY 5', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (6, 'FAC_NBR_06','US_TEST_06', 'TEST FACILITY 6', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (7, 'FAC_NBR_07','US_TEST_07', 'TEST FACILITY 7', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (8, 'FAC_NBR_08','US_TEST_08', 'TEST FACILITY 8', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (9, 'FAC_NBR_09','US_TEST_09', 'TEST FACILITY 9', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (10, 'FAC_NBR_10','US_TEST_10', 'TEST FACILITY 10', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (1, 'FAC_NBR_11','US_TEST_11', 'TEST FACILITY 11', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (2, 'FAC_NBR_12','US_TEST_12', 'TEST FACILITY 12', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (3, 'FAC_NBR_13','US_TEST_13', 'TEST FACILITY 13', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (4, 'FAC_NBR_14','US_TEST_14', 'TEST FACILITY 14', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (5, 'FAC_NBR_15','US_TEST_15', 'TEST FACILITY 15', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (6, 'FAC_NBR_16','US_TEST_16', 'TEST FACILITY 16', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (7, 'FAC_NBR_17','US_TEST_17', 'TEST FACILITY 17', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (8, 'FAC_NBR_18','US_TEST_18', 'TEST FACILITY 18', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (9, 'FAC_NBR_19','US_TEST_19', 'TEST FACILITY 19', SYSTIMESTAMP);
    insert into facility (account_id, facility_nbr, facility_code, facility_name, create_ts) values (10, 'FAC_NBR_20','US_TEST_20', 'TEST FACILITY 20', SYSTIMESTAMP);

    EXECUTE IMMEDIATE 'ALTER TABLE facility MODIFY id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY';
    insert into facility (id, account_id, facility_nbr, facility_code, facility_name, create_ts) values (-99, -99, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', SYSTIMESTAMP);
    insert into facility (id, account_id, facility_nbr, facility_code, facility_name, create_ts) values (-1, -1, 'ALL', 'ALL', 'ALL', SYSTIMESTAMP);
    EXECUTE IMMEDIATE 'ALTER TABLE facility MODIFY id NUMBER(19,0) GENERATED ALWAYS AS IDENTITY';

    COMMIT;
END;
