BEGIN
    INSERT ALL
        INTO LOAD_STATUS (STATUS_CODE, DESCRIPTION, CREATE_TS) VALUES ('RUNNING', 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STATUS (STATUS_CODE, DESCRIPTION, CREATE_TS) VALUES ('SUCCESS', 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STATUS (STATUS_CODE, DESCRIPTION, CREATE_TS) VALUES ('FAILED', 'ASDF', SYSTIMESTAMP)
        INTO LOAD_STATUS (STATUS_CODE, DESCRIPTION, CREATE_TS) VALUES ('UNKNOWN', 'ASDF', SYSTIMESTAMP)
    SELECT * FROM DUAL;
    
    COMMIT;
END;