DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'ERR_VALIDATION_01' AND owner = 'DAAS';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ERR_VALIDATION_01 CASCADE CONSTRAINTS PURGE';
    END IF;

    EXECUTE IMMEDIATE '
        CREATE TABLE ERR_VALIDATION_01 (
            LOAD_LOG_ID NUMBER NOT NULL,
            LOAD_LOG_DETAIL_ID NUMBER NOT NULL,
            FIELD_NAME VARCHAR2(255) NULL,
            TRANSFORMATION VARCHAR2(255) NULL,
            ERROR_CODE VARCHAR2(255) NULL,
            ERROR_MESSAGE VARCHAR2(255) NULL,
            CREATE_TS TIMESTAMP WITH TIME ZONE NULL
        )';

    
END;