DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'LOAD_LOG_DETAIL' AND owner = 'DAAS';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE LOAD_LOG_DETAIL CASCADE CONSTRAINTS PURGE';
    END IF;

    EXECUTE IMMEDIATE '
        CREATE TABLE LOAD_LOG_DETAIL (
            ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            LOAD_LOG_ID NUMBER NOT NULL,
            ALIAS VARCHAR2(250),
            STEP_CODE VARCHAR2(250) NOT NULL,
            SRC_TABLE VARCHAR2(250),
            TGT_TABLE VARCHAR2(250),
            STATUS_CODE VARCHAR2(250) NOT NULL,
            START_TS TIMESTAMP WITH TIME ZONE,
            END_TS TIMESTAMP WITH TIME ZONE,
            SQL CLOB,
            EXCEPTION_MSG CLOB,
            EXCEPTION_STACK CLOB,
            EXCEPTION_CODE VARCHAR2(250)
        )';

END;