DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'LOAD_STEP' AND owner = 'DAAS';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE LOAD_STEP CASCADE CONSTRAINTS PURGE';
    END IF;

    EXECUTE IMMEDIATE '
        CREATE TABLE LOAD_STEP (
            STEP_CODE VARCHAR2(255) NOT NULL PRIMARY KEY,
            ORDER NUMBER NOT NULL,
            DESCRIPTION VARCHAR2(255) NULL,
            CREATE_TS TIMESTAMP WITH TIME ZONE NULL
        )';

END;