DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'ERR_VALIDATION' AND owner = 'DAAS';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ERR_VALIDATION CASCADE CONSTRAINTS PURGE';
    END IF;

    EXECUTE IMMEDIATE '
        CREATE TABLE ERR_VALIDATION (
            LOAD_LOG_ID NUMBER NOT NULL,
            LOAD_LOG_DETAIL_ID NUMBER NOT NULL,
            SRC_TABLE VARCHAR2(255) NULL,
            TGT_TABLE VARCHAR2(255) NULL,
            FIELD_NAME VARCHAR2(255) NULL,
            VALIDATION VARCHAR2(4000) NULL,
            ERROR_CODE VARCHAR2(255) NULL,
            ERROR_MESSAGE VARCHAR2(4000) NULL,
            CREATE_TS TIMESTAMP WITH TIME ZONE NULL
        )';

    
END;