DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_tables WHERE table_name = 'LOAD_STATUS' AND owner = 'DAAS';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE LOAD_STATUS CASCADE CONSTRAINTS PURGE';
    END IF;

    EXECUTE IMMEDIATE '
        CREATE TABLE LOAD_STATUS (
            STATUS_CODE VARCHAR2(250) NOT NULL PRIMARY KEY,
            DESCRIPTION VARCHAR2(250),
            CREATE_TS TIMESTAMP WITH TIME ZONE
        )';

END;